### ISSUE TITLE
”看看“ 无考虑变量变为负数的情况

### ISSUE THREAD

**Issue by cjw0816** [ARIES-7/FIRST#2]
1.若多次进行减法，变量会变为负数，”如果 ..“语句是正确的，但”看看 ..“无输出。
![捕获9](https://user-images.githubusercontent.com/60734880/74209686-c3785b80-4cc3-11ea-82c2-be75925dccd6.PNG)

**Comment by ARIES-7** [comment]
if(a < 0)
	{	
		printf("负");
		a=-a;
	}



已解决。
